# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'internship-swift-2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for internship-swift-2
pod ‘Firebase/AnalyticsWithoutAdIdSupport’
pod 'Firebase/Auth'
pod 'GoogleSignIn', '~> 5.0'
pod 'Firebase/Firestore'
pod 'AppCenter'

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
end